name: VisionAPI CA Test

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTIONCA to start'
        required: true
        default: '...'
      Config:
        type: boolean
        description: Configuration only
      Application:
        type: boolean
        description: Application
      Authentication:
        type: boolean
        description: Authentication
      Authorization:
        type: boolean
        description: Authorization
      Cis:
        type: boolean
        description: Cis
      Customer:
        type: boolean
        description: Customer

jobs:

  # Correct branch and command message gate:
  workflow_allowed:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - run: |
          echo "Wrong command entered (\"PRODUCTION\" expected), or incorrect branch for this workflow (\"main\" expected)"
          exit 1
        if: "!contains(github.event.inputs.command, 'PRODUCTION') || steps.extract_branch.outputs.branch != 'main'"


  buildApplication:
    if: "${{github.event.inputs.Application}}"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Application"

  buildAuthentication:
    if: "${{github.event.inputs.Authentication}}"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authentication"

  buildAuthorization:
    if: "${{github.event.inputs.Authorization}}"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authorization"

  buildCis:
    if: "${{github.event.inputs.Cis}}"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Cis"

  buildCustomer:
    if: "${{github.event.inputs.Customer}}"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Customer"
