name: DTest for DEV

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type DEVELOPMENT to start'
        required: true
        default: '...'
    branches:
      - dev

jobs:
  initial-job:
      name: Initial operations
      runs-on: ubuntu-latest
      outputs:
        env: ${{ steps.vars.outputs.env }}
      steps:
      - name: Find branch name
        shell: bash
        run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - id: vars
        run: echo "::set-output name=env::$CURRENT_BRANCH"

  say_hello:
    if: "contains(github.event.inputs.command, 'DEVELOPMENT') && 'dev'==${{ env.CURRENT_BRANCH }}"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to DEVELOPMENT..........."
