name: DTest

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type DEPLOY to start'
        required: true
        default: 'Not deploy'
    branches:
      - dev

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Command = ${{ github.event.inputs.command }}"
