name: DTest

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTION to start'
        required: true
        default: '...'
    branches:
      - main

jobs:
  initial-job:
      name: Initial operations
      runs-on: ubuntu-latest
      outputs:
        env: ${{ steps.vars.outputs.env }}
      steps:
      - name: Find branch name
        shell: bash
        run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - id: vars
        run: echo "::set-output name=env::$CURRENT_BRANCH"


  # initial-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Extract branch name
  #     shell: bash
  #     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  #     id: extract_branch

  say_hello:
    if: "contains(github.event.inputs.command, 'PRODUCTION') && 'main'==${{ env.CURRENT_BRANCH }}"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to PRODUCTION!!!"
