name: DTest

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTION to start'
        required: true
        default: '...'
    branches:
      - main

jobs:

  # Correct branch and command message gate:
  workflow_allowed:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - run: echo "Wrong command entered (\"PRODUCTION\" expected), or incorrect branch for this workflow (\"main\" expected)"
        if: "contains(github.event.inputs.command, 'PRODUCTION') && steps.extract_branch.outputs.branch != 'main'"
      - run: exit 1
        if: "contains(github.event.inputs.command, 'PRODUCTION') && steps.extract_branch.outputs.branch != 'main'"

  say_hello:
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to PRODUCTION!!!! Yahooo!"
