name: DTest for DEV

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type DEVELOPMENT to start'
        required: true
        default: '...'
    branches:
      - dev

jobs:
  initial-job:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

  say_hello:
    if: "contains(github.event.inputs.command, 'DEVELOPMENT') && 'main'==${{ steps.extract_branch.outputs.branch }}"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to DEVELOPMENT..........."
