name: DTest for DEV

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type DEVELOPMENT to start'
        required: true
        default: '...'
    branches:
      - dev

jobs:

  say_hello:

    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - run: |
          echo "Going to DEVELOPMENT..........."
        if: "contains(github.event.inputs.command, 'DEVELOPMENT') && steps.extract_branch.outputs.branch == 'dev'"
