name: DTest for DEV

on:
  push:
    branches:
      - dev

jobs:

  go_to_dev_env:
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to DEVELOPMENT..........."
