name: VisionAPI CA Test

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTIONCA to start'
        required: true
        default: '...'
      DeploySettings:
        type: boolean
        description: Deploy settings
      DeployAllServices:
        type: boolean
        description: Deploy all services
      choice:
        type: choice
        description: Deploy service
        options:
        - Application
        - Authentication
        - Authorization
        - Cis
        - Customer
        - Logging
        - Program
        - Projects
        - SearchAPI
        - Services
        - System
        - Users
        - Utility
        - Workcenter
jobs:

  # Correct branch and command message gate:
  workflow_allowed:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - run: |
          echo "Wrong command entered (\"PRODUCTION\" expected), or incorrect branch for this workflow (\"main\" expected)"
          exit 1
        if: "!contains(github.event.inputs.command, 'PRODUCTION') || steps.extract_branch.outputs.branch != 'main'"


  deploySettings:
    if: "github.event.inputs.DeploySettings == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Application"

  buildApplication:
    if: "(contains(github.event.inputs.choice, 'Application') && github.event.inputs.DeployAllServices == 'false') || github.event.inputs.DeployAllServices == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Application"

  buildAuthentication:
    if: "(contains(github.event.inputs.choice, 'Authentication') && github.event.inputs.DeployAllServices == 'false') || github.event.inputs.DeployAllServices == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authentication"

  buildAuthorization:
    if: "(contains(github.event.inputs.choice, 'Authorization') && github.event.inputs.DeployAllServices == 'false') || github.event.inputs.DeployAllServices == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authorization"

  buildCis:
    if: "(contains(github.event.inputs.choice, 'Cis') && github.event.inputs.DeployAllServices == 'false') || github.event.inputs.DeployAllServices == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Cis"

  buildCustomer:
    if: "(contains(github.event.inputs.choice, 'Customer') && github.event.inputs.DeployAllServices == 'false') || github.event.inputs.DeployAllServices == 'true'"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Customer"



  deploy-all:
    if: "always()"
    needs: [workflow_allowed,deploySettings,buildApplication,buildAuthentication,buildAuthorization,buildCis,buildCustomer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deployApplication
        if: "contains(github.event.inputs.choice, 'Application') || github.event.inputs.DeployAllServices == 'true'"
        run: |
          echo "Deploying Application"

      - name: deployCis
        if: "contains(github.event.inputs.choice, 'Cis') || github.event.inputs.DeployAllServices == 'true'"
        run: |
          echo "Deploying Cis"
