name: VisionAPI CA Test

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTIONCA to start'
        required: true
        default: '...'
      choice:
        type: choice
        description: Which service to deploy?
        options:
        - Application
        - Authentication
        - Authorization
        - Cis
        - Customer
        - Logging
        - Program
        - Projects
        - SearchAPI
        - Services
        - System
        - Users
        - Utility
        - Workcenter
jobs:

  # Correct branch and command message gate:
  workflow_allowed:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - run: |
          echo "Wrong command entered (\"PRODUCTION\" expected), or incorrect branch for this workflow (\"main\" expected)"
          exit 1
        if: "!contains(github.event.inputs.command, 'PRODUCTION') || steps.extract_branch.outputs.branch != 'main'"


  buildApplication:
    if: "contains(github.event.inputs.choice, 'Application')"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Application"

  buildAuthentication:
    if: "contains(github.event.inputs.choice, 'Authentication')"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authentication"

  buildAuthorization:
    if: "contains(github.event.inputs.choice, 'Authorization')"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Authorization"

  buildCis:
    if: "contains(github.event.inputs.choice, 'Cis')"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Cis"

  buildCustomer:
    if: "contains(github.event.inputs.choice, 'Customer')"
    needs: [workflow_allowed]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "Building Customer"
