name: DTest

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Type PRODUCTION to start'
        required: true
        default: '...'
    branches:
      - main

jobs:
  say_hello:
    if: "contains(github.event.inputs.command, 'PRODUCTION') && 'main'==${GITHUB_REF##*/}"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Going to PRODUCTION!!!"
